### ISSUE TITLE
Dispose a feature is "tricky"

### ISSUE THREAD

**Issue by BraisGabin** [badoo/MVICore#105]
`Observable.wrap(feature).subscribe().dispose()` doesn't dispose the feature.

The problem is that `wrap` treats feature as an `ObservableSource`. And it doesn't have the _concept_ of dispose.

I know that you usually use the `Binder`s but if you don't this is kind of strange because you expose an `ObservableSource` that you need to dispose. So you end with things like this:

```kotlin
disposable += Observable.wrap(feature).subscribe()
disposable += Observable.wrap(feature.news).subscribe()
disposable += feature
```

An idea is to use a real `Observable`. This way all will work "as expected".

**Comment by zsoltk** [comment]
It's not just not a bug, it's actually desirable that it works this way.

The issue is that you seem to think about a `Feature` as if it was a cold observable. It's not, it's hot.

Imagine you inject your `Feature` to multiple scopes, and listen to its state updates. Now just because one of your scopes go away, and it disposes of its subscription to the state updates, it would be actually harmful to dispose of the `Feature` too.

Treat the `Feature` and subscriptions to its state updates as two different things. Keep using the `Binder` for subscription disposal, and dispose of the `Feature` only when it as a hot source should be killed definitely.

**Comment by BraisGabin** [comment]
I didn't think about a "scoped" feature... it have sense.
