### ISSUE TITLE
The problem of redundant view rendering

### ISSUE THREAD

**Issue by OlegSheliakin** [badoo/MVICore#80]
Hey everyone! 
How do you guys deal with problem of unnecessary view updates?
For example, you have a counter view which one is being updated each second with a new value. And you don't need to update other views, because their state is not being changed. It means that you have redundant view rendering.
Do you have any solution to avoid this?

**Comment by zsoltk** [comment]
@OlegSheliakin you can split the stream to multiple ones by mapping a different subset of the fields into each new stream, and call `.distinctUntilChanged()` on them individually. Alternatively, you can use single stream and do manual diff comparison with previous model field-by-field. 

Also keep in mind that you might be solving a non-existent problem. Unless you are actually heavily bombarding your view with tons of costly updates, the performance hit might be so negligible that you are causing more problems on the side of adding extra complexity to your code. A counter update once / 1 sec is basically nothing. I'd suggest to start with performance monitoring, and solve the bottlenecks where you actually have a problem, otherwise you'll be doing premature optimisation.

**Comment by OlegSheliakin** [comment]
I think splitting streams is not good idea, becasue in this way our state of screen will be splitted in two states and we will have two outputs. 
And it can bring states overlaping.

I didn't say that frequent view updates have big impact on perfomance, I told about redundancy of updates. 

And what if you have map and you need render markers on the map. We can conoare with previous state, but we have to store previous state?

**Comment by zsoltk** [comment]
You can do e.g. `stream.startWith(emptyElement).buffer(2, 1)`.
Also there's nothing wrong with splitting the stream, as you still have a single source of truth. Otherwise it's up to you to not make them overlapping if that bothers you (not that there's any problem with overlapping, just unnecessary except for some edge cases). But then again, if you have such  different view model streams, you might as well have different state machines for the two parts. You are not restricted to use only one to describe your whole screen.

**Comment by OlegSheliakin** [comment]
For example, let's  consider such simple case. You need to download a file from network. You have to show progress on percentage and some additional info (for example long description of file with image). How would you do? Would you split streamd for progress and description? And how would you do if you didn't need to show percentage but intermediate progress bar?

**Comment by zsoltk** [comment]
Probably I wouldn't bother. This case you describe is again in the zone where the performance hit is negligible.

**Comment by OlegSheliakin** [comment]
Ok , got your point
